db.getCollection('mcs')
    .drop();
db.getCollection('mcs')
    .insertMany([
      {
        _id: 'mcs0001',
        name: 'MK перший',
        description: 'Description Description Description Description Description Description Description Description ',
        parents: ['toys', 'wreaths'],
        createdAt: 1539004428299,
        updatedAt: 1539004428299,
        display: true,
        onMainPage: true,
        mainImage: 'default_product',
        views: 5,
        comments: [{
          comment: 'comment comment comment comment',
          commentator: 'hsdfsjdf',
          commentedAt: 1539004428500,
        }],
        likes: 10,
        dislikes: 10,
      },
      {
        _id: 'mcs0002',
        name: 'MK другий',
        description: 'Description Description Description Description Description Description Description Description ',
        parents: ['wreaths'],
        createdAt: 1539004428272,
        updatedAt: 1539004428272,
        display: true,
        onMainPage: true,
        mainImage: 'default_product',
        views: 15,
        comments: [{
          comment: 'comment comment comment comment',
          commentator: 'hsdfsjdf',
          commentedAt: 1539004428500,
        }],
        likes: 10,
        dislikes: 10,
      },
      {
        _id: 'mcs0003',
        name: 'MK третій',
        description: 'Description Description Description Description Description Description Description Description ',
        parents: ['wreaths'],
        createdAt: 1539004438272,
        updatedAt: 1539004438272,
        display: true,
        onMainPage: true,
        mainImage: 'default_product',
        views: 1,
        comments: [{
          comment: 'comment comment comment comment',
          commentator: 'hsdfsjdf',
          commentedAt: 1539004428500,
        }],
        likes: 10,
        dislikes: 10,
      },
      {
        _id: 'mcs0004',
        name: 'MK чт',
        description: 'Description Description Description Description Description Description Description Description ',
        parents: ['flowerBouquets'],
        createdAt: 1539004438272,
        updatedAt: 1539004439999,
        display: true,
        onMainPage: true,
        mainImage: 'default_product',
        views: 1,
        likes: 10,
        dislikes: 10,
      },
    ]);
