db.getCollection('catalogs')
.drop();
db.getCollection('catalogs')
.insertMany([
  { _id: 'home', name: 'Головна', ancestors: [], parent: 'null',
    auth: 'casual', order: 0, assets: ['catalog'], description: ''},
    {_id:'common', name:'Загальні', ancestors:['home'], parent :'home',
      auth: 'casual', order:1, assets:['catalog'], description:''},

      { _id: 'about', name: 'Про себе', ancestors: ['home', 'common'], parent: 'common',
        auth: 'casual', order: 1, assets: [''],description: ''},
      { _id: 'products', name: 'Мої роботи', ancestors: ['home', 'common'], parent: 'common',
        auth: 'casual', order: 2, assets: [''],description: ''},

        { _id: 'toys', ancestors: ['home', 'common', 'products'], parent: 'products', order: 1,
          assets: ['default_product'], prefix: 'toy',
          name: 'Ірашки', description: ''},
        { _id: 'wreaths', ancestors: ['home', 'common', 'products'], parent: 'products', order: 2,
          assets: ['default_product'], prefix: 'wrh',
          name: 'Віночки', description: ''},
        { _id: 'bouquets', ancestors: ['home', 'common', 'products'], parent: 'products', order: 3,
          assets: ['default_product'],  prefix: 'buq',
          name: 'Букети', description: ''},
          { _id: 'fruitBouquets', ancestors: ['home', 'common', 'products', 'bouquets'], parent: 'bouquets', order: 1,
            assets: ['default_product'],  prefix: 'buf',
            name: 'Букети з фруктів та овочів', description: ''},
          { _id: 'sweetBouquets', ancestors: ['home', 'common', 'products', 'bouquets'], parent: 'bouquets', order: 2,
            assets: ['default_product'],  prefix: 'bus',
            name: 'Букети з цукерок', description: ''},
          { _id: 'flowerBouquets', ancestors: ['home', 'common', 'products', 'bouquets'], parent: 'bouquets', order: 3,
            assets: ['default_product'],  prefix: 'buf',
            name: 'Букети з квітів', description: ''},
          { _id: 'otherBouquets', ancestors: ['home', 'common', 'products', 'bouquets'], parent: 'bouquets', order: 4,
            assets: ['default_product'],  prefix: 'buo',
            name: 'Інші букети', description: ''},

        { _id: 'decorative', ancestors: ['home', 'common', 'products'], parent: 'products', order: 4,
          assets: ['default_product'],  prefix: 'dcr',
          name: 'Декор', description: ''},
          { _id: 'weddingDecor', ancestors: ['home', 'common', 'products', 'decorative'], parent: 'decorative', order: 1,
            assets: ['default_product'], prefix: 'dcw',name: 'Весільний декор', description: ''},
          { _id: 'fotoZones', ancestors: ['home', 'common', 'products', 'decorative'], parent: 'decorative', order: 2,
            assets: ['default_product'], prefix: 'dcf', name: 'Фотозони', description: ''},

        { _id: 'knitting', ancestors: ['home', 'common', 'products'], parent: 'products', order: 5,
          assets: ['default_product'], prefix: 'kni',
          name: 'В\'язання', description: ''},
          { _id: 'mittens', ancestors: ['home', 'common', 'products', 'knitting'], parent: 'knitting', order: 1,
            assets: ['default_product'], prefix: 'knm',
            name: 'В\'язані рукавички', description: ''},
          { _id: 'hats', ancestors: ['home', 'common', 'products', 'knitting'], parent: 'knitting', order: 2,
            assets: ['default_product'], prefix: 'knh',
            name: 'В\'язані шапки', description: ''},
          { _id: 'pads', ancestors: ['home', 'common', 'products', 'knitting'], parent: 'knitting', order: 3,
            assets: ['default_product'], prefix: 'knp',
            name: 'Дитячі пінєтки', description: ''},


        { _id: 'scrapbooking', ancestors: ['home', 'common', 'products'], parent: 'products', order: 6,
          assets: ['default_product'], prefix: 'scr',
          name: 'Скрапбукінг', description: ''},
          { _id: 'albums', ancestors: ['home', 'common', 'products', 'scrapbooking'], parent: 'scrapbooking', order: 1,
            assets: ['default_product'], prefix: 'sca', name: 'Альбоми', description: ''},
          { _id: 'cards', ancestors: ['home', 'common', 'products', 'scrapbooking'], parent: 'scrapbooking', order: 2,
            assets: ['default_product'], prefix: 'scc', name: 'Листівки', description: ''},

  { _id: 'mcs', name: 'МК', ancestors: ['home', 'common'], parent: 'common', prefix: 'mcs',
        auth: 'casual', order: 3, prefix: 'to', assets: [''], description: ''},
      // { _id: 'contacts', name: 'Контакти', ancestors: ['home', 'common'], parent: 'common',
      //   auth: 'casual', order: 4, assets: [''],description: ''},

    {_id: 'system', name: 'Система', ancestors: ['home'], parent :'home',
      auth: 'guest', order: 2, assets:['catalog'], description:''},

      {_id: 'dashboard', name:'Dashboard', ancestors: ['home', 'system'], parent :'system',
        auth: 'guest', order: 1, assets:['catalog'],  description:''},
        {_id: 'profile', name: 'Профіль', ancestors: ['home', 'system', 'dashboard'], parent: 'dashboard',
          auth: 'guest', order: 1, assets: ['catalog'],description: ''},
        {_id: 'product-editor', name: 'Редактор виробів', ancestors: ['home', 'system', 'dashboard'], parent: 'dashboard',
          auth: 'manager', order: 2, assets: ['catalog'], description: ''},
        {_id: 'tools', name: 'Інструменти', ancestors: ['home', 'system', 'dashboard'], parent: 'dashboard',
          auth: 'manager', order: 5, assets: ['catalog'],description: ''},
        {_id: 'dashboard-signup', name: 'Реєстрація', ancestors: ['home', 'system', 'dashboard'], parent: 'dashboard',
          auth: 'manager', order: 6, assets: ['catalog'],description: ''},

      {_id: 'login', name: 'Увійти', ancestors: ['home', 'system'], parent: 'system',
        auth: 'casual', order: 2, assets: ['catalog'],description: ''},
      {_id: 'signup', name: 'Реєстрація', ancestors: ['home', 'system'], parent: 'system',
        auth: 'manager', order: 3, assets: ['catalog'],description: ''},
      {_id: 'logout', name: 'Вийти',ancestors: ['home', 'system'], parent: 'system',
        auth: 'guest', order: 4, assets: ['catalog'],description: ''},
]);
